---
title: "west"
output: html_document
date: "2023-05-22"
---
```{r}
#install.packages("Hmisc")
library(Hmisc)
library(lattice)  # trellis graphics
library(grid)
library(nlme)
library(lme4)
#install.packages("merTools")
library(merTools)
#install.packages("lmerTest")
library(lmerTest)
```


```{r setup, include=FALSE}
setwd("/Users/dc/test_stuff/repeated_measures/west_book")
rat_pup<-read.table("rat_pup/rat_pup.dat",h=T)
rat_pup
```


```{r cars}
attach(rat_pup)

g <- function(x)c(N=length(x),MEAN=mean(x,na.rm=TRUE),SD=sd(x,na.rm=TRUE),MIN=min(x,na.rm=TRUE),MAX=max(x,na.rm=TRUE))
summarize(weight,by=llist(treatment,sex),g)


```
```{r}
bwplot(weight ~ sex|treatment, data=rat_pup,aspect = 2, ylab="Birth Weights", 
    xlab="SEX",main = "Boxplots of birth weights for levels of treatment by sex")
```
```{r}
ranklit <- litsize+0.01*litter
sort(ranklit)
ranklit
ranklit <- factor(ranklit)

levels(ranklit) <- c( "1","2", "3","4","5","6","7","8","9","10", "11","12", "13","14","15","16","17","18","19","20", "21","22", "23","24","25","26","27")

ranklit
```
```{r}
bwplot(weight ~ranklit | treatment*sex, data=rat_pup,aspect = 2, ylab="Birth Weights", xlab="" )
```
```{r}
rat_pup$sex1[sex == "Female"] <- 1
rat_pup$sex1[sex == "Male"] <- 0
rat_pup
```
```{r}
model3.1.fit <- lme(weight ~ treatment + sex1 + litsize +
                          treatment:sex1, random = ~ 1 | litter,
                        data = rat_pup, method = "REML")
```
```{r}
#treatment <- relevel(treatment, ref = "High")

# Summary of model fit, along with F-tests.
summary(model3.1.fit)
anova(model3.1.fit)
```
```{r}
random.effects(model3.1.fit)

# Fit Model 3.1A.
model3.la.fit <- gls(weight ~ treatment + sex1 + litsize +
                           treatment:sex1, data = rat_pup)
anova(model3.1.fit, model3.la.fit) # Test Hypothesis 3.
```

```{r}
model3.2a.fit <- lme(weight ~ treatment + sex1 + litsize
                         + treatment:sex1, random = ~1 | litter, rat_pup, method = "REML",
                         weights  = varIdent(form = ~1 | treatment))

summary(model3.2a.fit)

# Test Hypothesis 3.2.
anova(model3.1.fit, model3.2a.fit)

```

```{r}
rat_pup$trtgrp[treatment == "Control"] <- 1
rat_pup$trtgrp[treatment == "Low" | treatment == "High"] <- 2

model3.2b.fit <- lme(weight ~ treatment + sex1 + litsize + treatment:sex1,
                       random  = ~ 1 | litter, rat_pup, method = "REML",
                       weights = varIdent(form = ~1 | trtgrp))

# Test Hypothesis 3.3.
anova(model3.2a.fit, model3.2b.fit)



```
```{r}
# Test Hypothesis 3.4.
anova(model3.1.fit, model3.2b.fit)

summary(model3.2b.fit)
```
```{r}
# Test Hypothesis 3.5.
anova(model3.2b.fit)

model3.3.ml.fit <- lme(weight ~ treatment + sex1 + litsize,
                         random = ~1 | litter, rat_pup, method = "ML",
                         weights = varIdent(form = ~1 | trtgrp))

model3.3a.ml.fit <- lme(weight ~ sex1 + litsize,
                          random = ~1 | litter, rat_pup, method = "ML",
                          weights = varIdent(form = ~1 | trtgrp))
```

```{r}
# Test Hypothesis 3.6.
anova(model3.3.ml.fit, model3.3a.ml.fit)
```

```{r}
model3.3.reml.fit <- lme(weight ~ sex1 + litsize + treatment,
                             random  = ~1 | litter, rat_pup, method = "REML",
                             weights = varIdent(form = ~1 | trtgrp))
summary(model3.3.reml.fit)
anova(model3.3.reml.fit)
```
```{r}
# Fit Model 3.1 (see chapter3_R_final.R for code to load the data).
model3.1.fit.lmer <- lmer(weight ~ treatment + sex1 + litsize +
                                treatment:sex1 + (1 | litter),
                              rat_pup, REML = T)

# View results and 95% confidence intervals.
summary(model3.1.fit.lmer)
confint(model3.1.fit.lmer)

# Display the random effects (EBLUPs) from the model.
ranef(model3.1.fit.lmer)

# Plot the predicted random effects along with measures of uncertainty.

REsim(model3.1.fit.lmer)
plotREsim(REsim(model3.1.fit.lmer))

# Code for obtaining p-values (if desired).


# Model 3.1.
model3.1.fit.lmer <- lmer(weight ~ treatment + sex1 + litsize +
                                treatment:sex1 + (1 | litter),
                              rat_pup, REML = T)

summary(model3.1.fit.lmer)
anova(model3.1.fit.lmer)

# Significant test for the variance component.
rand(model3.1.fit.lmer)
```
```{r}

trellis.device(color=F)

# Generate Figure 3.4

res <- resid(model3.3.reml.fit)
ratred <- data.frame(rat_pup, res)
ratred
histogram(~res | factor(trtgrp), data=ratred, layout=c(2,1), aspect = 2 , xlab = "Residual") 

# Generate Figure 3.5

qqnorm(model3.3.reml.fit, ~resid(.) | factor(trtgrp), layout=c(2,1), aspect = 2, id = 0.05) 

# Generate Figure 3.6 
 
plot(model3.3.reml.fit, resid(.) ~ fitted(.) | factor(trtgrp), layout=c(2,1), aspect=2, abline=0)

# Generate Figure 3.7 (note: these are conditional residuals)

attach(rat_pup)

ranklit <- litsize+0.01*litter
sort(ranklit)
ranklit
ranklit <- factor(ranklit)

levels(ranklit) <- c( "1","2", "3","4","5","6","7","8","9","10", "11","12", "13","14","15","16","17","18","19","20", "21","22","23","24","25","26","27")

ranklit

bwplot(resid(model3.3.reml.fit) ~ ranklit, data=model3.3.reml.fit, ylab="residual", xlab="litter")

# Influence diagnostics are not currently available.
```

