---
title: "Birth Notebook"
output: html_notebook
---
```{r}
install.packages("car")
install.packages("lm.beta")
library(car)
library("lm.beta")
```


```{r}
BIRTH<-read.csv("/Users/dc/test_stuff/analysis_factor/datasets_irc_workshop/BIRTH.csv")
colnames(BIRTH)
```
APGAR10 colunn is not an integer
```{r}
sapply(BIRTH,class)
```


```{r}
num=0
get_integer_cols<-function(df){
  for(i in 1:ncol(df)) {
    #print(colnames(df[i]))
    if(sapply(df[i],class)=="integer" || sapply(df[i],class)=="numeric"){
      num=num+1
      print(paste("col",i,":",colnames(df[i])))
    }
  }
  print(paste("num:",num))
  print(paste("num cols not integer or numeric:",ncol(birth)-num))
}
get_integer_cols(BIRTH)
```

```{r}
#rescaling births
BIRTH$gestation_days<-BIRTH$gestation*7
head(BIRTH$bwt,n=10)
head(BIRTH$bwt_pnds,n=10)
head(BIRTH$gestation,n=10)
head(BIRTH$gestation_days,n=10)
```

```{r}
plot(BIRTH$gestation,BIRTH$bwt_pnds,type="p",ylab="Birth Weight in Pounds",xlab="Gestation in Weeks")
m_bwt_pnds_ges <-lm(BIRTH$bwt_pnds ~ BIRTH$gestation)
abline(m_bwt_pnds_ges)
```
```{r}
res_m_bwt_pnds_ges<-resid(m_bwt_pnds_ges)
qqnorm(res_m_bwt_pnds_ges)
qqline(res_m_bwt_pnds_ges)
skewness(res_m_bwt_pnds_ges)
kurtosis(res_m_bwt_pnds_ges)
jarque.test(res_m_bwt_pnds_ges)
shapiro.test(res_m_bwt_pnds_ges)

```
```{r}
spreadLevelPlot(m_bwt_pnds_ges)

```

```{r}
ncvTest(m_bwt_pnds_ges)
```


```{r}
outlierTest(m_bwt_pnds_ges)
```



```{r}
plot(BIRTH$gestation_days,BIRTH$bwt,type="p",ylab="Birth Weight in Ounces",xlab="Gestation in Days")
abline(lm(BIRTH$bwt ~ BIRTH$gestation_days))
```

```{r}
model5<-lm(bwt_pnds~gestation,data=BIRTH)
summary(model5)
```



```{r}
model6<-lm(bwt~gestation_days,data=BIRTH)
summary(model6)
```
```{r}
NLSY<-nlsy
model7<-lm(PCS2000~CESD2000Total+Education2000+NumberBioStepAdoptChildHH2000+MCS2000,data=NLSY)
model7.1<-lm.beta(model7)
summary(model7.1)

```
```{r}
BIRTH<-birth
BIRTH$ln_last_preg<-log(BIRTH$last_preg)
BIRTH$inv_last_preg<-1/(BIRTH$last_preg)
BIRTH$sqrt_last_preg<-  (BIRTH$last_preg)
BIRTH$ln_pre_wgt<-log(BIRTH$pre_wgt)

```

```{r}
plot(BIRTH$mage,BIRTH$last_preg,type="p",ylab="last_preg",xlab="Mother's Age")
abline(lm(BIRTH$last_preg ~ BIRTH$mage))

plot(BIRTH$mage,BIRTH$sqrt_last_preg,type="p",ylab="sqrt_last_preg",xlab="Mother's Age")
abline(lm(BIRTH$sqrt_last_preg ~ BIRTH$mage))

plot(BIRTH$mage,BIRTH$ln_last_preg,type="p",ylab="ln_last_preg",xlab="Mother's Age")
abline(lm(BIRTH$ln_last_preg ~ BIRTH$mage))

##histograms of untransformed, square root, and natural log of months since last pregnancy
hist(BIRTH$last_preg)
hist(BIRTH$sqrt_last_preg)
hist(BIRTH$ln_last_preg)

```

```{r}
##Square Root transformation on Y
model8<-lm(sqrt_last_preg~mage+pre_wgt,data=BIRTH)
summary(model8)

##Natural log transformation on Y
model9<-lm(ln_last_preg~mage+pre_wgt,data=BIRTH)
summary(model9)

##Natural log transformation on X
model10<-lm(last_preg~mage+ln_pre_wgt,data=BIRTH)
summary(model10)

plot(BIRTH$ln_pre_wgt,BIRTH$last_preg,type="p",ylab="Months Since Last Pregnancy",xlab="ln_pre_wgt")
abline(lm(BIRTH$last_preg ~ BIRTH$ln_pre_wgt))

##Natural log transformation on both Y and X
model11<-lm(ln_last_preg~mage+ln_pre_wgt,data=BIRTH)
summary(model11)

plot(BIRTH$ln_pre_wgt,BIRTH$ln_last_preg,type="p",ylab="ln_last_preg",xlab="ln_pre_wgt")
abline(lm(BIRTH$ln_last_preg ~ BIRTH$ln_pre_wgt))


```

