---
title: "SIMR_demo"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(simr)
library(MASS)
```

#https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/2041-210X.12504

```{r}
#simulate a fixed and random effect
x<-rep(1:10)
g<-c('a','b','c')
is.factor(simdata$g) #use to determine if column is factor or not
is.numeric(simdata$z) # 
#----------------------
 
X<-expand.grid(x=x, g=g)
dim(X)
X
#fixed intercept and slop=e
b<-c(2,-0.1)
V1<-0.5
#random intercept and slope variance-covariance matrix
V2<-matrix(c(0.5,0.05,0.05,0.1),2)
#residual variance
s<-1
dim(V2)
V2
```
```{r}
head(simdata)
simdata
min(simdata$y)
max(simdata$y)
cat("---------------\n")
min(simdata$x)
max(simdata$x)
cat("---------------")
unique(simdata$g)
cat("---------------\n")
min(simdata$z)
max(simdata$z)
model1 <- makeLmer(y ~ x + (1|g), fixef=b, VarCorr=V1, sigma=s, data=X)
print(model1)
model2 <- makeGlmer(z ~ x + (x|g), family="poisson", fixef=b, VarCorr=V2, data=X)
print(model2)
powerSim(model1, nsim=20)
powerSim(model2, nsim=20)
```



```{r}
#from the paper, replicate changing the fixed effect(regression coefficient) then 
#how to find N=sample size to get fixed effect
#youtube <- glmer(Pr_rate ~ Day + (1|doctor), family="poisson", data=simdata)
#this is same as above but he put g=doctor, z as Pr_rate, x as day
model1 <- glmer(z ~ x + (1|g), family="poisson", data=simdata)
#doctor is a group and each one has separate intercept, random effect
#day or x is fixed effect.  
summary(model1)
#change size of fixed effect, x
#want 80% conficence as rule of thumb
fixef(model1)["x"] #prints out x regression coefficient
fixef(model1)["x"]<-.05 #reduce fixed effect to about half. I did not know this was possible
powerSim(model1) #simulate power with sample size of 10 per group. 
#'x', (95% confidence interval):
#      81.20% (78.64, 83.58)
#
#Test: z-test
#      Effect size for x is -0.11
#
#Based on 1000 simulations, (0 warnings, 0 errors)
#alpha = 0.05, nrow = 30
```
```{r}
model2<-extend(model1, along="x", n=20)
powerSim(model2)
pc2<-powerCurve(model2)
print(pc2)
plot(pc2)
```
```{r}
model3<-extend(model1, along="g", n=15)
pc3<-powerCurve(model3,along="g")
print(pc3)
plot(pc3)
```






```{r}
model4<-extend(model1,within="x+g",n=5)
pc4<-powerCurve(model4,within="x+g",breaks=1:5)
print(pc4)
plot(pc4)

```

```{r}
#https://besjournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2F2041-210X.12504&file=mee312504-sup-0001-AppendixS1.html

cbpp$obs <- 1:nrow(cbpp)
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd) + (1|obs), data=cbpp,
    family=binomial)
summary(gm1)$coef
```

