---
title: "Witness dataset"
output: html_notebook
---
None of the features are continuous. 

```{r}
witness<-read.csv("/Users/dc/test_stuff/analysis_factor/datasets_irc_workshop/witness.csv")
colnames(witness)
sapply(witness,class)

```
```{r}
plot(witness$SEX_WITN)
plot(witness$AGE_WITN)
plot(witness$SEX_PART)
plot(witness$ACCURATE)
plot(witness$HONEST)
plot(witness$MEMORY)
plot(witness$COGNITIV)
plot(witness$SENIOR_S)
plot(witness$SENIOR_H)
plot(witness$ACC_Cen)
plot(witness$AGEW_Cen)
plot(witness$COG_Cen)
plot(witness$HON_Cen)
plot(witness$MEM_Cen)
plot(witness$SENH_Cen)
plot(witness$SENS_Cen)
```

Plot histograms
```{r}
hist(witness$SEX_WITN)
hist(witness$AGE_WITN)
hist(witness$SEX_PART)
hist(witness$ACCURATE)
hist(witness$HONEST)
hist(witness$MEMORY)
hist(witness$COGNITIV)
hist(witness$SENIOR_S)
hist(witness$SENIOR_H)
hist(witness$ACC_Cen)
hist(witness$AGEW_Cen)
hist(witness$COG_Cen)
hist(witness$HON_Cen)
hist(witness$MEM_Cen)
hist(witness$SENH_Cen)
hist(witness$SENS_Cen)
```

witness$SENIOR_S is long tailed. We can transform with log

```{r}
na_count <-function (df) sapply(df, function(y) sum(is.na(y)))
na_count(witness)
```

