---
title: "gls_intro"
output: html_document
date: "2023-05-24"
---

```{r setup, include=FALSE}
library(nlme)
###install.packages("ggplot2")
library(ggplot2)
###install.packages("ggthemes")
library(ggthemes)
##install.packages("multcomp")
library(multcomp)
###install.packages("emmeans")
library(emmeans)
###install.packages("car")
library(car)
```


```{r}
set.seed(1500)

x <- rnorm(10000,100,12) # generate x with arbitrary values

y1 <- 10 + 15*x + rnorm(10000,0,5) # the first half of the dataset

y2 <-  -2 - 5*x + rnorm(10000,0,15) # the 2nd half of the data set with 3 times larger residual SD (15 vs. 5)

y <- c(y1, y2)
x.new <- c(x, x)

dummy.var <- c(rep(0, length(y1)), rep(1, length(y2))) # dummy variable to distinguish the first half of the dataset (y1) from the second (y2)

```
```{r}

# Calculate a normal regression model   

lm.mod <- lm(y~x.new*dummy.var)

summary(lm.mod)

```
```{r}
# Calculate a GLS without any options

gls.mod.1 <- gls(y~x.new*dummy.var)

summary(gls.mod.1)

```

```{r}
# GLS again, but allowing different residual variance for y1 and y2

gls.mod.2 <- gls(y~x.new*dummy.var, weights=varIdent(form=~1|dummy.var))

summary(gls.mod.2)
```
```{r}
setwd("/Users/dc/test_stuff/repeated_measures/data")

###We will need the teachers data set, the training data set, and the swallowing data set
###Long versions created in previous modules
teachers<-read.csv("longteachers.csv",header=T)
training<-read.csv("longtraining.csv",header=T)
swallowing<-read.csv("Swallowing.csv",header=T)
```
```{r}
teachers$t0TchExpCat<-cut(teachers$t0TchExp,breaks=c(0,3,Inf),include.lowest=F,labels=c(0,1))
###check on distribution
table(teachers$t0TchExpCat,exclude=NULL)

###scatterplot faceted by binary expectation
ggplot(na.exclude(teachers), aes(x=time, y=Rapport, color=factor(SubID)))+ geom_point() +
  geom_line() + theme_few()  + facet_wrap(~t0TchExpCat) + guides(color="none") +
  geom_smooth(method=lm,se=FALSE,color=1,size=1.5)+
  scale_color_discrete(name="Subject ID")+
  scale_x_continuous(breaks = seq(1:3),name="Time")
```
```{r}
model1<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",
            data=teachers,correlation=corSymm(form=~1|SubID),na.action=na.omit,
            weights=varIdent(form=~1|as.factor(time)),control=list(apVar=T))

###Examine the reuslts of the model; will not match SAS/SPSS results
summary(model1)

###Get type III F tests


```
```{r}
anova(model1,type="marginal")
```
```{r}
###Get Wald chi-squared tests
Anova(model1,type=3)

#
```
```{r}
## When you use a weights option, you need to extract the variance components and 
### hard-code the variance parameter estimates produced in the model summary
### to get a covariance matrix like those produced in SAS and SPSS: 
cors<-corMatrix(model1$modelStruct$corStruct)[[1]]
vars<-c(1.00000,1.242875,1.341622)^2*model1$sigma^2
covs<-outer(vars,vars,function(x,y) sqrt(x)*sqrt(y))
cors*covs
```
```{r}
####Compound symmetry
model2<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",
            data=teachers,correlation=corCompSymm(form=~1|SubID),
            na.action=na.omit,control=list(apVar=T))
###Get model summary
summary(model2) 
###Get variance matrix (easier without weights option!)
```
```{r}
###Compound symmetry
anova(model2,type="marginal")
```


```{r}
###Compound symmetry
Anova(model2,type=3)
```

```{r}
getVarCov(model2)
#Residual covariance matrix match
```

```{r}
###Autoregressive
model3<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",
            data=teachers,correlation=corAR1(form=~1|SubID),
            na.action=na.omit,control=list(apVar=T))
###Get model summary
summary(model3) 
```
```{r}
anova(model3,type="marginal")
```
```{r}
Anova(model3,type=3)
```

```{r}
getVarCov(model3)
```
```{r}
###Heterogeneous CS
model4<-gls(Rapport~as.factor(time)*t0TchExp, method="REML", data=teachers,
            correlation=corCompSymm(form=~1|SubID), weights=varIdent(form=~1|as.factor(time)),
            na.action=na.omit, control=list(apVar=T))
###Get model summary
summary(model4) 
```


```{r}
###Heterogeneous CS
anova(model4,type="marginal")
```


```{r}
Anova(model4,type=3)
```


```{r}
###Heterogeneous CS
cors<-corMatrix(model4$modelStruct$corStruct)[[1]]
vars<-c(1.00000,1.23069,1.38905)^2*model4$sigma^2
covs<-outer(vars,vars,function(x,y) sqrt(x)*sqrt(y))
cors*covs
```



```{r}
#####Heterogeneous autoregressive
model5<-gls(Rapport~as.factor(time)*t0TchExp, method="REML", data=teachers,
            correlation=corAR1(form=~1|SubID),weights=varIdent(form=~1|as.factor(time)),
            na.action=na.omit, control=list(apVar=T))
###Get model summary
summary(model5) 
###Get covariance matrix
cors<-corMatrix(model5$modelStruct$corStruct)[[1]]
vars<-c(1.00000,1.279944,1.426959 )^2*model5$sigma^2
covs<-outer(vars,vars,function(x,y) sqrt(x)*sqrt(y))
cors*covs
```


```{r}
###Diagonal
model6<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",data=teachers,
            weights=varIdent(form=~1|as.factor(time)),
            na.action=na.omit,control=list(apVar=T))
###Get model summary
summary(model6) 
###Get the diagonal variances
diag<-c(1.00000,1.239336,1.348378 )^2*model6$sigma^2
diag
```


```{r}
###Identity
model7<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",data=teachers,
            na.action=na.omit,control=list(apVar=T))
###Get the model summary
summary(model7)
#get the diagonal variances (the variance repeated 3 times)
diag<-c(rep(1,3))^2*model7$sigma^2
diag

```


```{r}
###toepilitz
model7_t<-gls(Rapport~as.factor(time)*t0TchExp, method="REML",data=teachers,
            correlation=corARMA(form=~1|SubID,p=2,q=0),
            na.action=na.omit,control=list(apVar=T))
###Get the model summary
summary(model7_t) 
###Get the variance matrix
getVarCov(model7_t)
```


```{r}
model8<-gls(Rapport~time*t0TchExp, method="REML",data=teachers,
            correlation=corAR1(form=~1|SubID), weights=varIdent(form=~1|as.factor(time)),
            na.action=na.omit,control=list(apVar=T))
###Get model summary
summary(model8) 
###Get variance matrix
cors<-corMatrix(model8$modelStruct$corStruct)[[1]]
vars<-c(1.00000,1.274222,1.421302  )^2*model8$sigma^2
covs<-outer(vars,vars,function(x,y) sqrt(x)*sqrt(y))
cors*covs
```


```{r}
#model1
325.3694	366.6784	-150.6847	
#model2 compound symmetrt
342.5581	370.0974	-163.2791	
#model3 ###Autoregressive
340.4904	368.0297	-162.2452	
#model4 hetergenous cs
330.7426	365.1667	-155.3713	

#model5 hetergenous autoregressive
328.7492	363.1734	-154.3746	

#model6 diagonal
445.9954	476.9772	-213.9977	
#model7
449.0265	473.1234	-217.5133	
#model7_t
340.0865	371.0683	-161.0433	

#model8_continuos
AIC.   BIC.   logLik
<dbl>. <dbl>. <dbl>
323.0629	350.6712	-153.5314	
```


```{r}

```


```{r}
```

