---
title: "rail_gls"
output: html_document
date: "2023-05-25"
---

```{r}
library(nlme)
library(ggplot2)
install.packages("nlraa")
library(nlraa)
plot(Orthodont)
plot(Orthodont,outer=TRUE)
```

```{r rail, echo=FALSE}

plot(Rail)
#from book Mixed Effects Models in S and S-Plus. 
#the gls function references this book
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
data(ChickWeight)
```

```{r}
flm<-lm(weight~Time, data=ChickWeight)
vlm<-var_cov(flm)
vlm
```

```{r}
fm1Rail.lm<-lm(travel~1, data=Rail)
fm1Rail.lm
summary(fm1Rail.lm)
fm1Rail_res = resid(fm1Rail.lm)
```

```{r}
fm1 <- lme(distance ~ age, Orthodont, random = ~ age | Subject)
# standardized residuals versus fitted values by gender
plot(fm1, resid(., type = "p") ~ fitted(.) | Sex, abline = 0)
# box-plots of residuals by Subject
plot(fm1, Subject ~ resid(.))
# observed versus fitted values by Subject
plot(fm1, distance ~ fitted(.) | Subject, abline = c(0,1))
```

```{r}
qqnorm(rstandard(fm1Rail.lm))
qqline(rstandard(fm1Rail.lm))
```

```{r}
library(MASS)
f<-data("faithful")
e.lm <- lm(eruptions ~ waiting, data=faithful) 
summary(e.lm)

```

```{r}
qqnorm(rstandard(e.lm) )
qqline(eruption.stdres) 
```
